apm install atom-beautify
apm install auto-detect-indentation
apm install auto-update-packages
apm install dash
apm install file-icons
apm install fonts
apm install git-blame
apm install git-time-machine
apm install highlight-selected
apm install merge-conflicts
apm install minimap
apm install script
apm install seti-syntax
apm install seti-ui
apm install sort-lines
apm install sublime-style-column-selection
apm install tablr
apm install terminal-plus
apm install tree-view-git-status
